---
title: "Data preparation"
author: "Pascale Caissy"
date: '2022-01-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("tidyverse")
library("FactoMineR")
library("ggplot2")
library("ggfortify")
library("reshape2")
library("nlme")
library("vegan")
```

```{r Functions to initialize}
jul.conv <- function(x) { 
  J <- julian( x, as.Date(paste0(format(x,"%Y"),"-01-01")))
  return(J[1])
}

prof_melange <- function(x){
  x <- x[!(is.na(x$Temp)),]
  for(l in 2:nrow(x)){
    r <- range(x$Temp[1:l], na.rm = TRUE)
    if(abs(diff(as.numeric(r))) > 0.5) {
      return(as.numeric(x$Pres[l]))
    }
    l = l+1
  }
  return(l-1)
}
```

# Obtain regional sea-ice data and calculate breakup date
```{r sea-ice breakup date}

# download ifremer yearly sea-ice concentration data that you need
## ftp://ftp.ifremer.fr/ifremer/cersat/products/gridded/psi-concentration/data/arctic/daily/netcdf/

################
library("ncdf4")
library("reshape2")
library("sf") #GIS data
library("dplyr") #pipeline
################
#Download lon lat grid
#downlaod north grid at ftp://ftp.ifremer.fr/ifremer/cersat/products/gridded/psi-concentration/data/grid_north_12km.nc.gz
#unzip north grid with 7z

grid <- nc_open("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Sea Ice/grid_north_12km.nc")# open north grid
lat<-ncvar_get(grid, "latitude") #get latitude variable
lon<-ncvar_get(grid,"longitude") #get longitude variable

lat<-melt(lat, value.name="lat") #arrange lat. in column 
lat$Var1<-NULL
lat$Var2<-NULL
lon<-melt(lon, value.name="lon") #arrange lon. in column
lon$Var1<-NULL
lon$Var2<-NULL
lat_lon<-cbind(lat, lon) #combine lon. and lat. 

lat_lon$lon_180 <- ifelse(lat_lon$lon >180, lat_lon$lon-360, lat_lon$lon) #convert longitude to a -180 to 180 format

shp <- read_sf("Data/InputFiles_dataPrep/CanadaGLmerged.shp")
points <- st_as_sf(lat_lon, coords = c("lon_180", "lat"), crs = st_crs(shp)) #transform lat long points to a GIS file

pnts <- points %>% mutate(
  intersection = as.integer(st_intersects(geometry, shp))
  , area = if_else(is.na(intersection), '', shp$Zone.name[intersection]) #intersect shp and points to get where on the grid each region is located
) 

########
#get years of interest
year <- c(2009,2010, 2011, 2014, 2015, 2016, 2017, 2018)


for(i in 1:length(year)) {
  
  # create a list of files and indicate its length
  f <- list.files(paste("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Sea Ice", year[i], sep = "/"), pattern="*.nc",full.names=F)
  lf<-length(f)
  
  # variable
  
  var1<-"concentration"
  var2='quality_flag'
  
  
  for (j in 1:lf) {
    
    # progress indicator
    print(paste(year[i], "Processing file",j,"from",length(f),sep=" "))
    # open netCDF file
    data<-nc_open(paste("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Sea Ice/", year[i], f[j], sep = "/"))
    
    # extract data
    seaice_conc<-ncvar_get(data, var1)
    seaice_conc<-melt(seaice_conc, value.name="seaice_conc")
    seaice_conc$Var1<-NULL
    seaice_conc$Var2<-NULL
    
    quality_flag<-ncvar_get(data, var2)
    quality_flag<-melt(quality_flag, value.name="qc")
    quality_flag$Var1<-NULL
    quality_flag$Var2<-NULL
    
    # matrix to data.frame
    dat.var<-cbind(lon,lat,seaice_conc, quality_flag)
    dat.mat <- as.data.frame(dat.var)
    colnames(dat.mat) <- c("lon","lat","seaice_conc", "quality_flag")
    dat.mat$reg <- pnts$area
    # select conditions
    dat.varSAtmp<-dat.mat[dat.mat$reg!="",]
    
    # prepare final data set
    date=f[j]
    year1<-((substr(date,1, 4)))
    month<-((substr(date, 5,6)))
    day<-(substr(date,7,8))
    date<-paste(year1, month, day, sep='-')
    #date<-as.Date(paste(year, month, day, sep='-'),format="%Y-%m-%d")
    if (nrow(dat.varSAtmp)>0){
      #dat.varSA<-data.frame(dat.varSAtmp,rep(seaice_conc,nrow(dat.varSAtmp)))
      #names(dat.varSA)<-c("lon","lat","seaice_conc")
      #seaice<-dat.varSAtmp$seaice_conc
      seaicemean<- aggregate(seaice_conc ~ reg, data = dat.varSAtmp, FUN = mean, na.rm = TRUE)
      seaicemean<-cbind(date, seaicemean)
      
      # save csv file
      fe<-file.exists(paste("regional_ice_new_",year1,".csv", sep=""))
      write.table(seaicemean,paste("regional_ice_new_",year1,".csv", sep=""),row.names=FALSE,col.names=!fe,sep=",",dec=".",append=fe)
      
      # close connection
      nc_close(data)
    }
    
  }
  
}

rm(dat.varSAtmp)
####################################
#########calculate ice bu date###############
library(lubridate)

bu <- NULL

for(i in 1:length(year)){
  ice <- read.csv(paste("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Sea Ice/regional_ice_new_", year[i],  ".csv", sep = ""))
  ice$date <- as.Date(ice$date)
  
  
  ice$week_num <- week(ice$date)
  
  ice_w <- aggregate(seaice_conc ~ week_num + reg, data = ice, FUN = mean)
  ice_bu <- ice_w %>% filter(seaice_conc < 50)
  
  reg_bu <- aggregate(week_num ~reg, data =ice_bu, FUN = min)
  reg_bu$bu_date <- parse_date_time(paste(year[i], reg_bu$week_num, 1, sep="/"),'Y/W/w')
  
  bu <- rbind(bu, reg_bu)
}

bu$year <- year(bu$bu_date)
colnames(bu) <- c("region", "week_name", "bu_date", "year")
bu$region <- as.character(bu$region)
bu$region[which(bu$region == "NE Greenland Sea")] <- "NEG"

```

#Calculate fish biomass per tow

```{r fish biomass per tow}
net_data <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Fish casts/BosaLarvae_NetsCatch_StationPascale-20210111.csv")

table(net_data$Flowmet_type)

net_data$rotor_constant <- ifelse(net_data$Flowmet_type == "GO", 26873/999999, 
                                  ifelse(net_data$Flowmet_type == "KC Denmark", 0.3, 
                                         ifelse(net_data$Flowmet_type == "TSK", 0.155, NA)))



net_data$volume.filtered <- with(net_data, (Flowmet_out - Flowmet_in) * rotor_constant *1)
net_data$volume.filtered <- ifelse(net_data$volume.filtered < 0,(99999-net_data$Flowmet_in + net_data$Flowmet_out)*net_data$rotor_constant, net_data$volume.filtered)

plot(volume.filtered~ Time_trawl_min, data = net_data)

net_data$volume.filtered[net_data$volume.filtered>1959] <- NA
net_data$volume.filtered[net_data$volume.filtered<70] <- NA
net_data$volume.filtered[net_data$Flag == "Inadequate"] <- NA
net_data$volume.filtered[c(41,31,32)] <- NA 
plot(volume.filtered ~ Time_trawl_min, data = net_data)

boxplot(volume.filtered ~ Mesh_um, data = net_data) 

lm.net <- lm(volume.filtered ~ Time_trawl_min, data = net_data)
summary(lm.net)

plot(volume.filtered ~ max_sampling_depth, data = net_data)

net_data$volume.filtered.est <- ifelse(is.na(net_data$volume.filtered), 
                                       ifelse(is.na(net_data$Other_net_volume), lm.net$coefficients[1] + lm.net$coefficients[2]*net_data$Time_trawl_min, net_data$Other_net_volume), net_data$volume.filtered)

plot(volume.filtered.est ~ Time_trawl_min, data = net_data)

net_data$indperm3 <- ifelse(net_data$max_sampling_depth >=51, net_data$X._ind/net_data$volume.filtered.est, NA)
sum(is.na(net_data$indperm3)) #19 stations à moins de 51m

net_data$indperm3all <- net_data$X._ind/net_data$volume.filtered.est
plot(indperm3all ~ max_sampling_depth, data = net_data,ylab = "Nombre d'individus par m3", xlab = "Profondeur", bty = "l")
net_data$indstandard <- net_data$indperm3all*net_data$max_sampling_depth/90
plot(indstandard ~ max_sampling_depth, data = net_data, ylab = "Nombre d'individus par m3 (standardisé)", xlab = "Profondeur", bty = "l")

net_station <- aggregate(data = net_data, indstandard ~ station + sampling_date + max_sampling_depth, FUN = mean)
write.csv(net_station, "/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Fish casts/net_data_CA_2021_01_15.csv")
```




# Integrate missing variables to gut content dataset
```{r gutcontent dataset}
gutcontent <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Stomach content/bosa stomach content_2021_01_07.csv", na.strings = "")  %>% select(-gear, -tow_type, -net_number, -mesh) %>% mutate(sampling_date = as.Date(sampling_date, "%Y-%m-%d"), date_gut_done = as.Date(date_gut_done, "%Y-%m-%d"))

str(gutcontent)
summary(gutcontent)

#add bu date
bu <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Sea Ice/bu.csv") %>% select(-X)
gutcontent2 <- merge(gutcontent, bu, by = c("region", "year"))


#treat CTD + zoo acoustic data + bosa biomass
station.CTD <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/station_list_PascaleCaissy_2021_01_16.csv", na.string = "")
test.CTD <- NULL
test.zoo <- NULL


for(i in 1:length(station.CTD$CTD_data_file)){
  print(paste("i =", i))
  vec.CTD <- c(strsplit(paste(station.CTD$CTD_data_file[i]), split =", "))[[1]]
  if(vec.CTD[1] == "NA"){
    test.CTD <- rbind(test.CTD, data.frame(station = station.CTD$station[i], sampling_date = station.CTD$sampling_date[i], max_fluo = NA, surf_sal_kgm3= NA, surf_temp_degC = NA, prof_mel = NA, cast_number = NA))
  } else{
    for (j in 1:length(vec.CTD)){
      file.dir.CTD <- paste("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - CTD/int_I_need", strftime(station.CTD$sampling_date, format = "%Y")[i], vec.CTD[j], sep = "/")
      CTD <- read.table(file.dir.CTD, na.string = "NaN", skip = station.CTD$lines_to_skip[i], header = TRUE,stringsAsFactors = FALSE)
      CTD[1,] <- NA
      #trouver la zone de mélange
      z <- prof_melange(CTD)
      surf_sal_kgm3 <- mean(head(as.numeric(as.character(CTD$Sal)), n=z), na.rm = TRUE)
      surf_temp_degC <- mean(head(as.numeric(as.character(CTD$Temp)), n=z), na.rm = TRUE)
      max_fluo <- max(as.numeric(as.character(CTD$Fluo)), na.rm = TRUE)
      test.CTD <- rbind(test.CTD, data.frame(station = station.CTD$station[i], sampling_date = station.CTD$sampling_date[i], max_fluo = max_fluo, prof_mel = z, surf_sal_kgm3= surf_sal_kgm3, surf_temp_degC = surf_temp_degC, cast_number = j))
      j = j+1
    }
  }
  file.dir.zoo <- paste("/Users/pascalecaissy/Dropbox/MSc 2019-2020", station.CTD$acoustic_file_zoo[i], sep = "/")
  if(is.na(station.CTD$acoustic_file_zoo[i])) {
    test.zoo <- rbind(test.zoo, data.frame(station = station.CTD$station[i], sampling_date = station.CTD$sampling_date[i], NASC_zoo = NA))
  } else if (station.CTD$acoustic_file_zoo[i] == "Data - Acoustic/ZoopJen2018.csv") {
    zoo <- read.csv(file.dir.zoo) %>% filter(as.character(region) == as.character(station.CTD$region[i]))
    NASC_zoo = mean(zoo$NASC_Int, na.rm = TRUE)
    test.zoo <- rbind(test.zoo, data.frame(station = station.CTD$station[i], sampling_date = station.CTD$sampling_date[i], NASC_zoo = NASC_zoo))
  } else {
    zoo <- read.csv(file.dir.zoo)
    NASC_zoo = mean(zoo$PRC_NASC, na.rm = TRUE)
    test.zoo <- rbind(test.zoo, data.frame(station = station.CTD$station[i], sampling_date = station.CTD$sampling_date[i], NASC_zoo = NASC_zoo))
  }
  i=i+1
}



test.CTD2 <- aggregate(data = test.CTD, . ~ sampling_date + station, FUN = mean, na.action = na.pass)
test.CTD2$max_fluo[is.nan(test.CTD2$max_fluo)] <- NA

biomass <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Fish casts/net_data_CA_2021_01_16.csv")
CTDbiomass <- merge(test.CTD2, biomass, by = c("station","sampling_date"))

#CTD GL----
CTD.GL <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - CTD/all/CTD_data_GL_20200107.csv")
zoo.GL.120 <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Acoustic/NEG/matrix120_leg1.csv") %>% select(-X)
zoo.GL.38 <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Acoustic/NEG/matrix38_leg1.csv") %>% select(-X)
station.GL <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Acoustic/NEG/GL Event log.csv")

zoo.GL <- zoo.GL.120
zoo.GL$Sv_mean_38 <- zoo.GL.38$Sv_mean
zoo.GL$deltaMVBS <- zoo.GL$Sv_mean-zoo.GL$Sv_mean_38

zoo.GL <- zoo.GL %>% filter(Depth_mean <=100 & Depth_mean >= 13.5, Lat_M > min(station.GL$LAT.N.decimal)-0.1 & Lat_M < max(station.GL$LAT.N.decimal)+0.1,Lon_M > min(station.GL$LONG.E.decimal*-1)-0.1 & Lon_M < max(station.GL$LONG.E.decimal*-1)+0.1) #0.1deg = 11.1km/6 miles nautiques
mean.NASC.GL <- mean(zoo.GL$NASC)

stationsGL <- unique(gutcontent[gutcontent$region == "NEG", c("station", "sampling_date")])
biomass.GL <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Fish casts/density_data_GL_20200304.csv") 
biomass.GL <- biomass.GL %>% mutate(sampling_date = as.Date(Date)) %>% filter(SDepthCat == "B")

test.GL <- NULL
for(i in stationsGL$station) {
  print(i)
  biomass <- biomass.GL[biomass.GL$Station == i, "bosa_dens_PC_indm.3"]
  CTD <- CTD.GL[CTD.GL$Stn == i,]
  z <- prof_melange(CTD)
  surf_sal_kgm3 <- mean(head(as.numeric(as.character(CTD$Sal)), n=z), na.rm = TRUE)
  surf_temp_degC <- mean(head(as.numeric(as.character(CTD$Temp)), n=z), na.rm = TRUE)
  test.GL <- rbind(test.GL, data.frame(station = i, sampling_date = as.factor(stationsGL[stationsGL$station == i, "sampling_date"]), max_fluo = -1000, prof_mel = z, surf_sal_kgm3= surf_sal_kgm3, surf_temp_degC = surf_temp_degC, max_sampling_depth = NA, indstandard = biomass ,NASC_zoo = mean.NASC.GL))
}

CTDzoobiomass <-  merge(CTDbiomass[,-7], test.zoo)
testALL <- rbind(CTDzoobiomass, test.GL)

gutcontent3 <- merge(gutcontent2, testALL)

#add open water day
gutcontent <- gutcontent3 %>% 
  mutate(open_water_day = sapply(sampling_date, FUN = jul.conv) - sapply(as.Date(bu_date), FUN = jul.conv)) 

```

# Correct dataset problems
```{r streamline gutcontent dataset}
#some larvae id may repeat themselves year after year
length(unique(gutcontent$larvae_id)) #I know I dissected 339 fish for now, so some ids are the same
gutcontent$unique_fish_id <- ifelse(gutcontent$region == "NEG", 
                                    paste("NEG", gutcontent$larvae_id, sep = "-"),
                                    paste(gutcontent$year, gutcontent$larvae_id, sep = "-"))

length(unique(gutcontent$unique_fish_id))

#Calculate missing standard lengths
summary(gutcontent$standard_length)
missing.length <- gutcontent[is.na(gutcontent$standard_length), c("year", "region", "larvae_id", "preserved_standard_length", "comments")]
sum(is.na(gutcontent$standard_length))
missing.pres.length <- gutcontent[is.na(gutcontent$preserved_standard_length), c("year", "region", "larvae_id", "standard_length", "comments")]
sum(is.na(missing.pres.length$standard_length)) #even though i could not measure preserved length, i still have standard length

fish.with.SL <- aggregate(prey_id ~ unique_fish_id + standard_length + preserved_standard_length, data = gutcontent, FUN = length, na.action = na.pass)
plot(preserved_standard_length ~ standard_length, data = fish.with.SL) #seems robust
lm.SL <-lm(preserved_standard_length ~ standard_length, data = fish.with.SL)
summary(lm.SL)

test <- gutcontent %>% filter(is.na(standard_length)) %>% select(unique_fish_id) %>% filter(!duplicated(.$unique_fish_id))

gutcontent$est_standard_length <- ifelse(is.na(gutcontent$standard_length), (gutcontent$preserved_standard_length - lm.SL$coefficients[1])/lm.SL$coefficients[2], gutcontent$standard_length)
summary(gutcontent$est_standard_length)
all.equal(gutcontent$est_standard_length, gutcontent$standard_length) #seems to have worked and not just copied standard_length column
any(is.na(gutcontent$est_standard_length)) #no NA left
rm(fish.with.SL)

test <- gutcontent[is.na(gutcontent$height_anus), c("unique_fish_id","preserved_height_anus")] %>%filter(!duplicated(.$unique_fish_id))
test <- gutcontent[is.na(gutcontent$preserved_height_anus) & is.na(gutcontent$height_anus), c("unique_fish_id","preserved_height_anus")] %>%filter(!duplicated(.$unique_fish_id))

fish.with.HA <- aggregate(prey_id ~ unique_fish_id + height_anus + preserved_height_anus+standard_length, data = gutcontent, FUN = length, na.action = na.pass)

plot(preserved_height_anus ~ height_anus, data = fish.with.HA)
lm.HA <- lm(preserved_height_anus ~ height_anus, data = fish.with.HA)
summary(lm.HA)

plot(height_anus ~ standard_length, data = fish.with.HA)
lm.HASL <- lm(height_anus ~ standard_length, data = fish.with.HA)
summary(lm.HASL)

gutcontent$est_height_anus <- ifelse(is.na(gutcontent$height_anus) &!is.na(gutcontent$preserved_height_anus), (gutcontent$preserved_height_anus-lm.HA$coefficients[1])/lm.HA$coefficients[2], 
                                     ifelse(is.na(gutcontent$height_anus) &is.na(gutcontent$preserved_height_anus), (gutcontent$standard_length*lm.HASL$coefficients[2])+lm.HASL$coefficients[1],
                                            gutcontent$height_anus))
summary(gutcontent$est_height_anus)

#Correct prey typos
unique(gutcontent$prey_id)
gutcontent$prey_id <- as.character(gutcontent$prey_id)
gutcontent$prey_id[gutcontent$prey_id == " oithona similis"] <- "oithona similis"
gutcontent$prey_id[gutcontent$prey_id == "triconia sp"] <- "triconia borealis"
gutcontent$prey_id[gutcontent$prey_id == "egg "] <- "egg"
gutcontent$prey_id[gutcontent$prey_id == "microcalanus sp "] <- "microcalanus sp"
gutcontent$stade <- as.character(gutcontent$stade)
gutcontent$cop_or_naup[which(gutcontent$prey_id == "oithona similis" & is.na(gutcontent$cop_or_naup))] <- "c"
gutcontent$cop_or_naup[which(gutcontent$prey_id == "onceaidae sp" & is.na(gutcontent$cop_or_naup))] <- "c"
gutcontent$cop_or_naup[which(gutcontent$prey_id == "pseudocalanus sp" & is.na(gutcontent$cop_or_naup))] <- "c"
gutcontent$prey_length[which(gutcontent$prey_length == 4621)] <- 462
gutcontent$prey_id <-as.factor(gutcontent$prey_id)
gutcontent$prey_id <- droplevels(gutcontent$prey_id)
gutcontent$prey_id_nonstade <- ifelse(is.na(gutcontent$cop_or_naup) == FALSE, paste(gutcontent$prey_id, gutcontent$cop_or_naup, sep = " "), paste(gutcontent$prey_id))

gutcontent$prey_length <- ave(gutcontent$prey_length,gutcontent$prey_id_nonstade,FUN=function(x) 
  ifelse(is.na(x), mean(x,na.rm=TRUE), x))
gutcontent$prey_height <- ave(gutcontent$prey_height,gutcontent$prey_id_nonstade,FUN=function(x) 
  ifelse(is.na(x), mean(x,na.rm=TRUE), x))
unique(gutcontent$prey_id_nonstade)[order(unique(gutcontent$prey_id_nonstade))]

#assign unknowns to a species----
table(gutcontent$prey_id_nonstade)[c("unknown n", "unknown c")]
1572/24646 #6.3% unknown n
1870/24646 #7.6% unknown c

gutcontent$is_it_fragment[which(is.na(gutcontent$is_it_fragment))] <- "N" 
table(gutcontent[gutcontent$prey_id_nonstade %in% c("unknown c", "unknown n"),c("prey_id_nonstade", "is_it_fragment")])
(1440+949)/(1572+1870)#most unknowns are fragments (~2/3)
range(gutcontent$prey_length[gutcontent$prey_id_nonstade %in% c("unknown c", "unknown n")], na.rm = TRUE)
range(gutcontent$prey_length[gutcontent$prey_id_nonstade %in% c("unknown c")], na.rm = TRUE)
range(gutcontent$prey_length[gutcontent$prey_id_nonstade %in% c("unknown n")], na.rm = TRUE)

gutcontent$prey_reass <- gutcontent$prey_id_nonstade

for(j in 1:3){
  for(i in 1:nrow(gutcontent)) {
    if(gutcontent$prey_reass[i] == "unknown n"){
      fishID <- gutcontent$unique_fish_id[i]
      samp_bag_all <- na.omit((gutcontent[gutcontent$unique_fish_id == fishID & gutcontent$cop_or_naup == "n", "prey_id_nonstade"]))
      samp_bag_medium <- na.omit((gutcontent[gutcontent$unique_fish_id == fishID & gutcontent$cop_or_naup == "n" & gutcontent$prey_length > 272, "prey_id_nonstade"]))
      samp_bag_big <- na.omit((gutcontent[gutcontent$unique_fish_id == fishID & gutcontent$cop_or_naup == "n" & gutcontent$prey_length > 462, "prey_id_nonstade"]))
      if(!length(samp_bag_all)){
        gutcontent$prey_reass[i] <- gutcontent$prey_reass[i]
      } else if(gutcontent$prey_length[i]>272 & gutcontent$prey_length[i] <= 462 & !!length(samp_bag_medium)){
        gutcontent$prey_reass[i] <- sample(samp_bag_medium, size = 1)
      } else if(gutcontent$prey_length[i]>272 & gutcontent$prey_length[i] <= 462 & !length(samp_bag_medium)){
        gutcontent$prey_reass[i] <- gutcontent$prey_reass[i] 
      } else if(gutcontent$prey_length[i] > 462 & !!length(samp_bag_big)){
        gutcontent$prey_reass[i] <- sample(samp_bag_big, size = 1)
      } else if(gutcontent$prey_length[i] > 462 & !length(samp_bag_big)){
        gutcontent$prey_reass[i] <- gutcontent$prey_reass[i]
      } else {
        gutcontent$prey_reass[i] <- sample(samp_bag_all, size = 1)
      }
    } else if(gutcontent$prey_reass[i] == "unknown c"){
      fishID <- gutcontent$unique_fish_id[i]
      samp_bag_all <- na.omit(gutcontent[gutcontent$unique_fish_id == fishID & gutcontent$cop_or_naup == "c", "prey_id_nonstade"])
      samp_bag_medium <- na.omit(gutcontent[gutcontent$unique_fish_id == fishID & gutcontent$cop_or_naup == "c" & gutcontent$prey_length > 600, "prey_id_nonstade"])
      samp_bag_big <- na.omit(gutcontent[gutcontent$unique_fish_id == fishID & gutcontent$cop_or_naup == "c" & gutcontent$prey_length > 1500, "prey_id_nonstade"]) 
      if(!length(samp_bag_all)){
        gutcontent$prey_reass[i] <- gutcontent$prey_reass[i]
      } else if(gutcontent$prey_length[i] > 600 & gutcontent$prey_length[i] <= 1500 & !!length(samp_bag_medium)){
        gutcontent$prey_reass[i] <- sample(samp_bag_medium, size = 1)
      } else if(gutcontent$prey_length[i]>600 & gutcontent$prey_length[i] <= 1500 & !length(samp_bag_medium)){
        gutcontent$prey_reass[i] <- gutcontent$prey_reass[i] 
      } else if(gutcontent$prey_length[i] > 1500 & !!length(samp_bag_big)){
        gutcontent$prey_reass[i] <- sample(samp_bag_big, size = 1)
      } else if(gutcontent$prey_length[i] > 1500 & !length(samp_bag_big)){
        gutcontent$prey_reass[i] <- gutcontent$prey_reass[i]
      } else {
        gutcontent$prey_reass[i] <- sample(samp_bag_all, size = 1)
      }
    } else {
      gutcontent$prey_reass[i] <- gutcontent$prey_reass[i]
    }
    i = i+1
  }
  j = j+1
}
table(gutcontent$prey_reass)[c("unknown n", "unknown c")]
gutcontent$NASC_zoo <- ave(gutcontent$NASC_zoo,gutcontent$region,FUN=function(x) 
  ifelse(is.na(x), mean(x,na.rm=TRUE), x))
gutcontent$surf_sal_kgm3 <- ave(gutcontent$surf_sal_kgm3,gutcontent$region,FUN=function(x) 
  ifelse(is.na(x), mean(x,na.rm=TRUE), x))
gutcontent$surf_temp_degC <- ave(gutcontent$surf_temp_degC,gutcontent$region,FUN=function(x) 
  ifelse(is.na(x), mean(x,na.rm=TRUE), x))
gutcontent$prof_mel <- ave(gutcontent$prof_mel,gutcontent$region,FUN=function(x) 
  ifelse(is.na(x), mean(x,na.rm=TRUE), x))
write.csv(gutcontent, "/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Stomach content/gutcontent_bosa_20220123.csv")
```


# Carbon content calculations based on formulas
```{r carbon}
gutcontent <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Stomach content/gutcontent_bosa_20220123.csv")
eggSACK <- function(x){
  x$num_eggs_in_egg_sack <- NA
  x$diam_eggs_in_egg_sack <- NA
  for (i in 1:dim(x)[1]){
    if(x$prey_id[i] == "egg sack"){
      char <- as.character(x$comments_on_gut_content[i])
      char_sub <- substr(char, start = 1, stop = nchar(char)-2)
      splitting <- strsplit(char_sub, split = "x")
      x$num_eggs_in_egg_sack[i] <- as.numeric(splitting[[1]][1])
      x$diam_eggs_in_egg_sack[i] <- as.numeric(splitting[[1]][2])
    }
    i = i+1
  }
  return(x)
}
#....calculate carbon content----
gutcontent <- eggSACK(gutcontent)
gutcontent$carbon_ug <- with(gutcontent,
                             ifelse(prey_reass %in% c("pseudocalanus sp/metridia longa n", "pseudocalanus sp", "pseudocalanus sp n", "unknown nc", "unknown n", "calanoid sp n", "microcalanus sp n", "microcalanus sp  n"), 0.447*(10^(2.515*log10(prey_length/1000)+0.975)),
                                    ifelse(prey_reass == "egg", 0.14*10^-6*(4/3*pi*(prey_length/2)^3), 
                                           ifelse(prey_reass %in% c("calanus sp n", "calanus glacialis n"), 4.29*10^-6*prey_length^2.05,
                                                  ifelse(prey_reass %in% c("unknown c", "calanoid sp c", "calanoid sp", "microcalanus sp c", "calanus finmarchicus c", "chiridus sp c", "heterorhabdus norvegicus c", "paraheterorhabdus compactus c", "spinocalanus sp c","scolecithricella sp c"), 10^(3.07*log10(prey_length)-8.37),
                                                         ifelse(prey_reass %in% c("pseudocalanus sp c", "pseudocalanus sp/acartia sp c"), 0.447*10^(2.85*log10(prey_length)-7.62),
                                                                ifelse(prey_reass %in% c("oithona similis c", "oithona similis", "triconia borealis c", "oncea sp c", "onceaidae sp c", "onceaidae sp", "cyclopoid sp c"), 9.4676*10^-7*prey_length^2.16,
                                                                       ifelse(prey_reass %in% c("calanus glacialis c", "calanus sp c"), 4.742*(prey_length/1000)^3.452,
                                                                              ifelse(prey_reass %in% c("bivalve larvae", "cirripedia sp n", "cirripedia sp"), 3.06*10^-8*prey_length^2.88,
                                                                                     ifelse(prey_reass %in% c("metridia longa n", "acartia sp n"), 3.18*10^-9*prey_length^3.31,
                                                                                            ifelse(prey_reass == "metridia longa c", 7.498*(prey_length/1000)^3.225,
                                                                                                   ifelse(prey_reass == "limacina helicina", 10^(3.102*log10(prey_length/1000)+1.469),
                                                                                                          ifelse(prey_reass == "appendicularian sp" | prey_reass == "oikopleura sp", 8.2*10^-8*prey_length^2.70,
                                                                                                                 ifelse(prey_reass == "coscinodiscus sp", 10^(-0.541+0.811*log10(((prey_length/2)^3*4*pi)/3))*10^-6,
                                                                                                                        ifelse(prey_reass == "fritillaria sp", 10^-9.45*prey_length^3.241,
                                                                                                                               ifelse(prey_reass == "acartia sp c", 1.023*10^-8*prey_length^2.906,
                                                                                                                                      ifelse(prey_reass == "eurytemora sp c", 0.447*(10^(2.96*log10(prey_length)-7.604)),
                                                                                                                                             ifelse(prey_reass == "podon sp" | prey_reass == "podon sp n",10^(4.15*log10(prey_length)-11.15)*10^-3,
                                                                                                                                                    ifelse(prey_reass == "calanus hyperboreus c", 7.263*(prey_length/1000)^3.106,
                                                                                                                                                           ifelse(prey_reass %in% c("digested matter", "unknown","vertebrae"), 0.4*109.08*(pi*((prey_height/1000)/2)^2*(prey_length/1000))^0.9591, 
                                                                                                                                                                  ifelse(prey_reass %in% c("oithona similis n", "cyclopoid sp n"), 5.545*10^-8*prey_length^2.71,
                                                                                                                                                                         ifelse(prey_reass == "chaetognath sp", 10^(3.16*log10(prey_length/1000)-1.29),
                                                                                                                                                                                ifelse(prey_reass == "boroecia maxima", 0.346*exp(3.8686*(prey_length/1000))*0.4,
                                                                                                                                                                                       ifelse(prey_reass == "harpacticoid sp c", exp(1.03*log(prey_length)-7.07),
                                                                                                                                                                                              ifelse(prey_reass == "paraeuchaeta sp c", 0.447*1000*(0.0075*(prey_length/1000)^3.274+ (0.07*0.0075*(prey_length/1000)^3.274)),
                                                                                                                                                                                                     ifelse(prey_reass %in% c("polychaetae larvae", "vers"), 1.42*10^-4*prey_length^1.47, 
                                                                                                                                                                                                            ifelse(prey_reass %in% c("decapoda sp", "decapoda sp meta", "crustacea sp meta"), 0.4*10^(1.08*prey_length/1000-0.89), 
                                                                                                                                                                                                                   ifelse(prey_reass == "egg sack", num_eggs_in_egg_sack*0.14*10^-6*(4/3*pi*(diam_eggs_in_egg_sack/2)^3),
                                                                                                                                                                                                                          ifelse(prey_reass == "amphipod sp", (log10(prey_length/1000)-0.063)/0.277,
                                                                                                                                                                                                                                 NA)))))))))))))))))))))))))))))

gutcontent$carbon_mg <- gutcontent$carbon_ug/1000

write.csv(gutcontent, "/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Stomach content/gutcontent_bosa_carbon20220123.csv")
```


# Prepare fish dataset
```{r gutcontent to fish}
gutcontent2 <- read.csv("/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Stomach content/gutcontent_bosa_carbon20220123.csv")%>% select(-X)
gutcontent2$prey_id_comb <- with(gutcontent2, ifelse( prey_reass %in% c("triconia borealis c", "oithona similis c", "onceaidae sp c", "oncea sp c", "cyclopoid sp c"), "cyclopoidae sp c", 
                                                      ifelse( prey_reass %in% c("appendicularian sp", "fritillaria sp", "oikopleura sp"), "appendicularia", 
                                                              ifelse( prey_reass %in% c("calanus sp n", "calanus glacialis n"), "calanus sp n",
                                                                      ifelse(prey_reass %in% c("calanoid sp", "calanoid sp c", "heterorhabdus norvegicus c", "metridia longa c", "chiridus sp c", "acartia sp c", "eurytemora sp c", "pseudocalanus sp/acartia sp c", "paraheterorhabdus compactus c", "paraeuchaeta sp c", "scolecithricella sp c", "spinocalanus sp c", "microcalanus sp c"), "calanoid sp c", 
                                                                             ifelse(prey_reass %in% c("calanoid sp n", "acartia sp n", "pseudocalanus sp/metridia longa n", "metridia longa n", "cyclopoid n", "microcalanus sp n", "microcalanus sp  n", "oithona similis n", "cyclopoid sp n", "unknown n"), "other copepodite n", 
                                                                                    ifelse(prey_reass %in% c("egg","egg sack"), "egg",
                                                                                           ifelse(prey_reass %in% c("fecal pellet","radiolarian sp","vers", "unknown", "chaetognath sp", "vertebrae", "trematoda sp", "parasite","polychaetae larvae", "digested matter", "crustacea sp meta", "amphipod sp", "decapoda sp meta", "euphausiacea sp", "decapoda sp", "boroecia maxima", "cirripedia sp", "cirripedia sp n", "podon sp", "coscinodiscus sp"), "other",
                                                                                                  ifelse(prey_reass %in% c("unknown c", "harpacticoid sp c", "unknown nc"),"other copepodite sp",
                                                                                                         ifelse(prey_reass %in% c("calanus sp c", "calanus finmarchicus c"), "calanus sp c", 
                                                                                                                as.character(prey_reass)))))))))))
unique(gutcontent2$prey_id_comb)

fs.fish.data <- aggregate(carbon_mg ~ unique_fish_id + est_standard_length + est_height_anus + region + year + station + sampling_date + bu_date + open_water_day + NASC_zoo + surf_sal_kgm3 + surf_temp_degC + prof_mel + indstandard, data = gutcontent2, FUN = sum, na.action = na.omit)

fs.fish.data$fish_WW <- (0.0055*((fs.fish.data$est_standard_length/10)^3.19))*1000 
fs.fish.data$feeding_success <- fs.fish.data$carbon_mg/fs.fish.data$fish_WW

prey_range <- aggregate(prey_length ~ unique_fish_id, data = gutcontent2, FUN = function(x, na.rm = TRUE) {max(x) - min(x)})
prey_min <- aggregate(prey_length ~ unique_fish_id, data = gutcontent2, FUN=min, na.rm = TRUE)
prey_max <- aggregate(prey_length ~ unique_fish_id, data = gutcontent2, FUN=max, na.rm = TRUE)
prey_median <- aggregate(prey_length ~ unique_fish_id, data = gutcontent2, FUN=median, na.rm = TRUE) 
fs.fish.data$prey_range_um <- prey_range$prey_length
fs.fish.data$prey_min_um <- prey_min$prey_length
fs.fish.data$prey_max_um <- prey_max$prey_length
fs.fish.data$prey_median_um <- prey_median$prey_length

plot(est_height_anus ~ est_standard_length, data = fs.fish.data)
lm.HASL <- lm(est_height_anus ~ est_standard_length, data = fs.fish.data)
summary(lm.HASL)
plot(lm.HASL)
fs.fish.data$fish_cond <- residuals(lm.HASL)

prey_matrix <- data.table::dcast(data.table::setDT(gutcontent2), unique_fish_id~prey_reass, length)
fish.data.prey <- merge(fs.fish.data, prey_matrix)

prey_matrix_comb <- data.table::dcast(data.table::setDT(gutcontent2), unique_fish_id~prey_id_comb, length)
fish.data.prey.comb <- merge(fs.fish.data, prey_matrix_comb)

write.csv(fish.data.prey, "/Users/pascalecaissy/Dropbox/MSc 2019-2020/Data - Stomach content/fish_data_PC_20220123.csv")

```

